development:
  adapter: postgresql
  pool: 5
  # these are our new parameters
  encoding: UTF-8
  database: foodapp_development
  host: localhost
  username: postgres
  password: soyyo1889

test:
  # this won't work 
  adapter: postgresql
  encoding: unicode
  database: foodapp_test
  host: localhost
  pool: 5
  username: postgres
  password: soyyo1889

production:
  # this won't work 
  adapter: postgresql
  encoding: unicode
  database: foodapp_production
  pool: 5
  username: postgres
  password: 
